from __future__ import annotations

import logging
from typing import Any, Dict, Optional, Tuple

import requests

from lifelens.avatar.config import settings

logger = logging.getLogger(__name__)


class VoicePlaybackService:
    """
    Voice behavior adapter.

    Default behavior returns the stored familiar voice sample.
    If configured, a remote clone provider can synthesize audio and gracefully
    fall back to the stored sample when unavailable.
    """

    def __init__(self):
        self.provider = (settings.AVATAR_VOICE_CLONE_PROVIDER or "sample").lower()
        self.endpoint = settings.AVATAR_VOICE_CLONE_ENDPOINT
        self.timeout_seconds = max(settings.AVATAR_VOICE_CLONE_TIMEOUT_MS, 1000) / 1000.0

    def clone_enabled(self) -> bool:
        return self.provider == "http" and bool(self.endpoint)

    def resolve_audio(self, text: str, person_payload: Dict[str, Any]) -> Tuple[Optional[str], str]:
        """
        Returns (audio_base64, source).

        Source is one of:
        - "voice_clone": generated by configured clone provider
        - "stored_sample": familiar voice sample already stored with person
        - "none": no audio available
        """
        sample_audio = person_payload.get("audio_base64") if isinstance(person_payload, dict) else None

        if self.provider in {"sample", "stored", "none", "off", "disabled"}:
            return sample_audio, "stored_sample" if sample_audio else "none"

        if self.provider == "http":
            cloned_audio = self._resolve_http_clone(text=text, person_payload=person_payload, sample_audio=sample_audio)
            if cloned_audio:
                return cloned_audio, "voice_clone"
            return sample_audio, "stored_sample" if sample_audio else "none"

        # Unknown provider: stay safe and return existing sample.
        return sample_audio, "stored_sample" if sample_audio else "none"

    def _resolve_http_clone(self, text: str, person_payload: Dict[str, Any], sample_audio: Optional[str]) -> Optional[str]:
        if not self.endpoint or not text.strip() or not sample_audio:
            return None

        payload = {
            "text": text,
            "sample_audio_base64": sample_audio,
            "person_name": person_payload.get("name"),
            "relation": person_payload.get("relation"),
            "metadata": {
                "notes": person_payload.get("notes"),
                "relation_tags": person_payload.get("relation_tags", []),
            },
        }

        try:
            response = requests.post(self.endpoint, json=payload, timeout=self.timeout_seconds)
            response.raise_for_status()
            data = response.json() if response.content else {}
            audio_base64 = data.get("audio_base64")
            if isinstance(audio_base64, str) and audio_base64:
                return audio_base64
        except Exception as exc:
            logger.warning("Voice clone provider failed, using stored sample fallback: %s", exc)

        return None


voice_playback_service = VoicePlaybackService()
